config/routes.rb
Rails.application.routes.draw do
  resources :act_joins
  resources :user_logs
  resources :types, only: [:index, :show]

  resources :topics, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :activities
    resources :blogs
    resources :topics
    resources :types

    root to: "users#index"
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :activities, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'draft-events', to: 'activities#draft'
  get 'activity/:id', to: 'activities#show', as: "activity_show"
  get 'user-dashboard', to: 'user_dashboard#index'
  post "user-dashboard"            => "user_dashboard#update"
  get 'user-profile', to: 'user_dashboard#profile'
  get 'user-activities', to: 'user_dashboard#active_activities'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'ranking', to: 'pages#ranking'
  get 'tweets', to: 'pages#tweets'

  resources :blogs, :activities do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/act_join.rb
class ActJoin < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  validates :user_id, presence: true
  validates :activity_id, presence: true

  scope :act_by, ->(user) { where(user_id: user.id) }

  # after_create_commit { ActJoinBroadcastJob.perform_later(self) }
end

app/controllers/act_joins_controller.rb
class ActJoinsController < ApplicationController
  def index
    @act_joins = ActJoin.all
  end

  def new
    @act_joins = ActJoin.new
  end

  def create
    @act_joins = current_user.act_joins.new(act_join_params)

    respond_to do |format|
      if @act_joins.save!
        format.html { redirect_to '/activities', notice: 'You successfully joined the event.' }
        format.json { render :show, status: :created, location: @act_joins }
      else
        format.html { render :new }
        format.json { render json: @act_joins.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def act_join_params
    params.require(:act_joins).permit(:user_id, :activity_id)
  end
end

app/helpers/act_joins_helper.rb
module ActJoinsHelper
end

app/views/act_joins/_act_join.html.erb
<table class="table table-striped table-hover">
    <tr>
      <th>
        <%= act_join.user.name %>
      </th>
    </tr>
</table>

app/views/act_joins/_act_join_form.html.erb
<%= form_for :act_joins, url: act_joins_path do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :activity_id, :value => @activity_events.id %>
  <%= f.submit 'Join', class: 'btn btn-success' %>
<% end %>



  

app/views/act_joins/_acts.html.erb
<div class="album py-5">
  <div class="container">
    <h3 class="pb-3 mb-4 font-italic border-bottom">
      All Your Joined Events
    </h3>
    <div class="row">
      <% @act_join.each do |act| %>
        <div class="col-md-3 bttm">
          <div class="card-body bord">
            <%= image_tag act_img(act.activity.image, 'image'), height:'195px', width:'190px' %>
            <p class="card-text"><strong><%= link_to act.activity.title.truncate_words(4), activity_show_path(act) %></strong></p>
            <div class="d-flex justify-content-between align-items-center">
              <ul class="list-unstyled mb-0">
                <li><small class="text-muted"><strong>Start Date: </strong><%= act.activity.start_date %></small></li>
                <li><small class="text-muted"><strong>Miles: </strong><%= act.activity.miles %></small></li>    
                <li><small class="text-muted"><strong>Status: </strong><%= act.activity.status %></small></li>
              </ul>   
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/act_joins/index.html.erb
<%= render @act_joins %>