config/routes.rb
Rails.application.routes.draw do
  resources :act_joins
  resources :user_logs
  resources :types, only: [:index, :show]

  resources :topics, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :activities
    resources :blogs
    resources :topics
    resources :types

    root to: "users#index"
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :activities, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'draft-events', to: 'activities#draft'
  get 'activity/:id', to: 'activities#show', as: "activity_show"
  get 'user-dashboard', to: 'user_dashboard#index'
  post "user-dashboard"            => "user_dashboard#update"
  get 'user-profile', to: 'user_dashboard#profile'
  get 'user-activities', to: 'user_dashboard#active_activities'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'ranking', to: 'pages#ranking'
  get 'tweets', to: 'pages#tweets'

  resources :blogs, :activities do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/act_join.rb
class ActJoin < ApplicationRecord
  belongs_to :user
  belongs_to :activity

  validates :user_id, presence: true
  validates :activity_id, presence: true

  scope :act_by, ->(user) { where(user_id: user.id) }

  # after_create_commit { ActJoinBroadcastJob.perform_later(self) }
end

app/models/activity.rb
require 'date'

class Activity < ApplicationRecord
  belongs_to :type
  belongs_to :user
  has_many :act_joins, dependent: :destroy

  enum status: { draft: 0, live: 1, ended: 2 }

  validates_presence_of :title, :miles, :status, :description, :start_date, :end_date, :user_id, :type_id

  mount_uploader :image, ActivityUploader

  scope :activities_by, ->(user) { where(user_id: user.id) }

  scope :all_except, ->(activity) { where.not(status: 2) }

  def self.draft
    where(status: 'draft')
  end

  def self.live
    where(status: 'live')
  end

  def self.ended
    where(status: 'ended')
  end

  def self.by_position
    order("position ASC")
  end

  def self.recent
    order("created_at DESC")
  end

  after_create :toggle_status

  def toggle_status
    if self.end_date < Date.today
      self.update(status: 2)
    elsif self.start_date > Date.today
      self.update(status: 0)
    else self.start_date <= Date.today
      self.update(status: 1)
    end
  end

end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  validates_presence_of :title, :body, :topic_id, :user_id

  mount_uploader :picture, BlogUploader

  scope :blogs_by, ->(user) { where(user_id: user.id) }

  belongs_to :topic
  belongs_to :user

  has_many :comments, dependent: :destroy

  def self.recent
    order("created_at DESC")
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email, :id
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title

  has_many :blogs

  def self.with_blogs
    includes(:blogs).where.not(blogs: { id: nil })
  end

  def self.by_position
    order("position ASC")
  end
end

app/models/type.rb
class Type < ApplicationRecord
  validates_presence_of :title

  has_many :activities

  def self.with_activities
    includes(:activities).where.not(activities: { id: nil })
  end
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                          ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :blogs
  has_many :activities
  has_many :comments, dependent: :destroy
  has_many :user_logs
  has_many :act_joins, dependent: :destroy

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/models/user_dashboard.rb
class UserDashboard < ApplicationRecord

  scope :activities_by, ->(user) { where(user_id: user.id) }
  scope :blogs_by, ->(user) { where(user_id: user.id) }
  scope :user_log_by, ->(user) { where(user_id: user.id) }
  scope :act_by, ->(user) { where(user_id: user.id) }
  
  def self.by_position
    order("position ASC")
  end

  def self.recent
    order("created_at DESC")
  end

end  

app/models/user_log.rb
class UserLog < ApplicationRecord
  belongs_to :user

  validates_presence_of :user_id, :miles, :day

  scope :user_log_by, ->(user) { where(user_id: user.id) }

  def self.miles
    order("miles DESC")
  end

  def self.recent_day
    order("day DESC")
  end
end

app/helpers/act_joins_helper.rb
module ActJoinsHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def image_generator
    "logo-rtd.png"
  end

  def act_img img, type
    if img.model.image?
      img
    else type == 'image'
      image_generator
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper style = ''
    if current_user.is_a?(GuestUser)
      (link_to "Register", new_user_registration_path, class: style) + "  ".html_safe +
      (link_to "Login", new_user_session_path, class: style)  
    else
      link_to "Logout", destroy_user_session_path, method: :delete, class: style
    end
  end

  def my_copyright
    Kamara::Renderer.copyright 'Kamara', 'All rights reserved'
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def picture_generator
    "logo-rtd.png"
  end

  def blog_img img, type
    if img.model.picture?
      img
    else type == 'picture'
      picture_generator
    end 
  end

  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML 
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def twitter_parser tweet
    
    regex = %r{
      \b
      (
        (?: [a-z][\w-]+:
         (?: /{1,3} | [a-z0-9%] ) |
          www\d{0,3}[.] |
          [a-z0-9.\-]+[.][a-z]{2,4}/
        )
        (?:
         [^\s()<>]+ | \(([^\s()<>]+|(\([^\s()<>]+\)))*\)
        )+
        (?:
          \(([^\s()<>]+|(\([^\s()<>]+\)))*\) |
          [^\s`!()\[\]{};:'".,<>?«»“”‘’]
        )
      )
    }ix

    tweet.gsub(regex) do |url|
      "<a href='#{url}' target='_blank'>#{url}</a>"
    end.html_safe
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/user_logs_helper.rb
module UserLogsHelper
end

app/views/layouts/activity.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'activities', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/trans_nav", location: 'top'  %>
    
    <%= yield %>
    
    <%= render "shared/trans_footer" %> 

    <%= render 'shared/alerts' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render "shared/trans_nav" %>
    
    <%= yield %>

    <%= render "shared/trans_footer" %> 

    <%= render 'shared/alerts' %>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/trans_nav" %>
    <%= yield %>
    <%= render "shared/trans_footer" %>  
    <%= render 'shared/alerts' %>
  </body>
</html>

app/views/layouts/user_dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <title>User Dasboard</title>   
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'user_dashboard', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <%= yield %>
  </body>
</html>  

app/views/shared/_activity_search_bar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <i><%= link_to fa_icon('plus-square-o'), new_activity_url if logged_in?(:site_admin) || logged_in?(:user) && current_user.try(:name) != "Guest User"  %></i>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <strong><i class="nav-link">Activity Types:</i></strong>
        </li>
        <li class="nav-item">
          <%= link_to "All Activities", activities_path , class: "nav-link" %>
        </li>
        <% @sidebar_types.each do |type| %>
        <li class="nav-item">
          <%= link_to type.title, type_path(type), class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_admin_dropdown.html.erb
<li>
  <%= link_to "Admin Dashboard", admin_root_path, class: 'nav-link' %>
</li>
<li class="divider"></li>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Race The Day App Alert", sticky: false, :time => 2500) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Race The Day App Error", sticky: false, :time => 2500) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "Race The Day App Notification", sticky: false, :time => 2500) %>
<% end %>

app/views/shared/_blog_sidebar.html.erb
<div class="p-3">
  <h4 class="font-italic">Topic</h4>
  <ol class="list-unstyled mb-0">
    <li><%= link_to "All Blogs", blogs_path %></li>
    <% @sidebar_topics.each do |topic| %>
      <li><%= link_to topic.title, topic_path(topic) %></li>
    <% end %>
  </ol>
</div>

app/views/shared/_trans_footer.html.erb
<footer>
<hr>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="https://twitter.com/search?q=running%20motivation&src=typd">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="mailto:belalkamara@gmail.com?subject=Run The Day">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://www.instagram.com/explore/tags/running/?hl=en">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted"><%= my_copyright %></p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_trans_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="#">Race the Day!</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <%= link_to "Home", root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link js-scroll-trigger" href="#about">About</a>
        </li>
        <li class="nav-item">
          <%= link_to "Blog", blogs_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Activity", activities_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Ranking", ranking_path, class: 'nav-link' %>
        </li>

        <li class="dropdown pull-right nav-item menu-link">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle">Menu<strong class="caret"></strong></a>
          <ul class="dropdown-menu">

            <% if current_user.try(:role) == :site_admin %>
              <%= render 'shared/admin_dropdown' %>
            <% end %>

            <% if current_user.try(:role) == :user && current_user.try(:name) != "Guest User" %>
              <%= render 'shared/user_dropdown' %>
            <% end %>    
            
            <li>
              <%= login_helper 'nav-link' %>
            </li>

          </ul>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/shared/_user_dash_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <%= link_to "Home", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
        <%= link_to "Dashboard", user_dashboard_path, class: 'nav-link' %>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Active Activities">
        <%= link_to "Active Activities", user_activities_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_user_dropdown.html.erb
<li>
  <%= link_to "User Dashboard", user_dashboard_path, class: 'nav-link' %>
</li>
<li class="divider"></li>