config/routes.rb
Rails.application.routes.draw do
  resources :act_joins
  resources :user_logs
  resources :types, only: [:index, :show]

  resources :topics, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :activities
    resources :blogs
    resources :topics
    resources :types

    root to: "users#index"
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :activities, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'draft-events', to: 'activities#draft'
  get 'activity/:id', to: 'activities#show', as: "activity_show"
  get 'user-dashboard', to: 'user_dashboard#index'
  post "user-dashboard"            => "user_dashboard#update"
  get 'user-profile', to: 'user_dashboard#profile'
  get 'user-activities', to: 'user_dashboard#active_activities'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'ranking', to: 'pages#ranking'
  get 'tweets', to: 'pages#tweets'

  resources :blogs, :activities do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/user_dashboard.rb
class UserDashboard < ApplicationRecord

  scope :activities_by, ->(user) { where(user_id: user.id) }
  scope :blogs_by, ->(user) { where(user_id: user.id) }
  scope :user_log_by, ->(user) { where(user_id: user.id) }
  scope :act_by, ->(user) { where(user_id: user.id) }
  
  def self.by_position
    order("position ASC")
  end

  def self.recent
    order("created_at DESC")
  end

end  

app/controllers/user_dashboard_controller.rb
class UserDashboardController < ApplicationController
  layout "user_dashboard"

  def index
    @draft_blogs = Blog.draft.blogs_by current_user

    @pub_blogs = Blog.published.blogs_by current_user

    @draft_acts = Activity.draft.activities_by current_user   

    @ended_acts = Activity.ended.activities_by current_user  

    @live_acts = Activity.live.activities_by current_user
  end

  def sort
     
  end

  def active_activities
    @user_logs = UserLog.new

    @user_log = UserLog.recent_day.page(params[:page]).per(6).user_log_by current_user

    @act_joins = ActJoin.act_by current_user

    @activity_events = Activity.recent.page(params[:page]).per(9).by_position

    @act_join = ActJoin.all.act_by current_user
  end

end

app/views/user_dashboard/_draft_act.html.erb
<div class="col-md-3 bttm">
  <div class="card-body bord">
    <%= image_tag act_img(draft_act.image, 'image'), height:'195px', width:'190px' %>
    <p class="card-text"><strong><%= link_to draft_act.title.truncate_words(4), activity_show_path(draft_act) %></strong></p>
    <div class="d-flex justify-content-between align-items-center">
      <ul class="list-unstyled mb-0">
        <li><small class="text-muted"><strong>Start Date: </strong><%= draft_act.start_date %></small></li>
        <li><small class="text-muted"><strong>Miles: </strong><%= draft_act.miles %></small></li>    
        <li><small class="text-muted"><strong>Status: </strong><%= draft_act.status %></small></li> 

        <%= link_to 'Destroy', draft_act, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>

        <%= link_to "Edit Activity", edit_activity_path(draft_act), class: 'btn btn-warning btn-sm' %>
      </ul>   
    </div>
  </div>
</div>

app/views/user_dashboard/_draft_blog.html.erb
<div class="col-md-3 bttm">
  <div class="card-body bord">
    <%= image_tag blog_img(draft_blog.picture, 'picture'), height:'195px', width:'190px', class: "center-block" %>
    <p class="card-text"><strong><%= link_to draft_blog.title.truncate_words(4), draft_blog %></strong></p>
    <div class="d-flex justify-content-between align-items-center">
      <ul class="list-unstyled mb-0">
      <li><small class="text-muted"><strong>Published </strong><%= distance_of_time_in_words(draft_blog.created_at, Time.now) %> ago</small></li>
      <li><small class="text-muted"><strong>Status: </strong><%= draft_blog.status %></small></li>

      <%= link_to 'Destroy', draft_blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>

      <%= link_to "Edit Blog", edit_blog_path(draft_blog), class: 'btn btn-warning btn-sm' %>
      </ul>
    </div>
  </div>
</div>

app/views/user_dashboard/_ended_act.html.erb
<div class="col-md-3 bttm">
  <div class="card-body bord">
    <%= image_tag act_img(ended_act.image, 'image'), height:'195px', width:'190px' %>
    <p class="card-text"><strong><%= link_to ended_act.title.truncate_words(4), activity_show_path(ended_act) %></strong></p>
    <div class="d-flex justify-content-between align-items-center">
      <ul class="list-unstyled mb-0">
        <li><small class="text-muted"><strong>Start Date: </strong><%= ended_act.start_date %></small></li>
        <li><small class="text-muted"><strong>Miles: </strong><%= ended_act.miles %></small></li>    
        <li><small class="text-muted"><strong>Status: </strong><%= ended_act.status %></small></li> 

        <%= link_to 'Destroy', ended_act, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>

        <%= link_to "Edit Activity", edit_activity_path(ended_act), class: 'btn btn-warning btn-sm' %>
      </ul>   
    </div>
  </div>
</div>

app/views/user_dashboard/_live_act.html.erb
<div class="col-md-3 bttm">
  <div class="card-body bord">
    <%= image_tag act_img(live_act.image, 'image'), height:'195px', width:'190px' %>
    <p class="card-text"><strong><%= link_to live_act.title.truncate_words(4), activity_show_path(live_act) %></strong></p>
    <div class="d-flex justify-content-between align-items-center">
      <ul class="list-unstyled mb-0">
        <li><small class="text-muted"><strong>Start Date: </strong><%= live_act.start_date %></small></li>
        <li><small class="text-muted"><strong>Miles: </strong><%= live_act.miles %></small></li>    
        <li><small class="text-muted"><strong>Status: </strong><%= live_act.status %></small></li> 
        
        <%= link_to 'Destroy', live_act, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>

        <%= link_to "Edit Activity", edit_activity_path(live_act), class: 'btn btn-warning btn-sm' %> 
      </ul>   
    </div>
  </div>
</div>

app/views/user_dashboard/_pub_blog.html.erb
<div class="col-md-3 bttm">
  <div class="card-body bord">
    <%= image_tag blog_img(pub_blog.picture, 'picture'), height:'195px', width:'190px', class: "center-block" %>
    <p class="card-text"><strong><%= link_to pub_blog.title.truncate_words(4), pub_blog %></strong></p>
    <div class="d-flex justify-content-between align-items-center">
      <ul class="list-unstyled mb-0">
      <li><small class="text-muted"><strong>Published </strong><%= distance_of_time_in_words(pub_blog.created_at, Time.now) %> ago</small></li>
      <li><small class="text-muted"><strong>Status: </strong><%= pub_blog.status %></small></li>

      <%= link_to 'Destroy', pub_blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>

      <%= link_to "Edit Blog", edit_blog_path(pub_blog), class: 'btn btn-warning btn-sm' %>
      </ul>
    </div>
  </div>
</div>

app/views/user_dashboard/active_activities.html.erb
<%= render 'shared/user_dash_nav' %>

<div class="content-wrapper">
  <div class="container-fluid">
    
    <div class="row">
      <div class="col-md-3">
        <div class="card">
          <div class="card-body">
            <%= render 'user_logs/form' %>
          </div>
        </div>
      </div>

      <div class="col-md-8">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>
                User Name
              </th>
              <th>
                Day
              </th>
              <th>
                Miles
              </th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <%= render @user_log %>
          </tbody>
        </table>
        <div>
        <%= paginate @user_log %>
        </div>
      </div>
    </div>
    <hr>
      <%= render 'act_joins/acts'%>
  </div>
</div>

app/views/user_dashboard/index.html.erb
<div>
<%= render 'shared/user_dash_nav' %>

  <div class="content-wrapper">
    <div class="container-fluid">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">My Dashboard</li>
      </ol>

      <div class="container">
        <%= link_to 'Create Blog', new_blog_path, class: 'btn btn-primary' %>
        <%= link_to 'Create Activity', new_activity_path, class: 'btn btn-primary' %>
        <%= link_to "Edit Account", edit_user_registration_path, class: 'btn btn-primary' %>
      </div>
      
      <div class="album py-5">
        <div class="container">
          <h3 class="pb-3 mb-4 font-italic border-bottom">
            All Your Activity Events
          </h3>
          <div class="row">            
            <%= render partial: 'draft_act', collection: @draft_acts %>
            <%= render partial: 'live_act', collection: @live_acts %>
            <%= render partial: 'ended_act', collection: @ended_acts %>
          </div>
          <h3 class="pb-3 mb-4 font-italic border-bottom">
            All Your Blogs
          </h3>
          <div class="row">
            <%= render partial: 'draft_blog', collection: @draft_blogs %>
            <%= render partial: 'pub_blog', collection: @pub_blogs %>
          </div>
        </div>  
      </div>
    </div>
  </div>
</div>

app/views/user_dashboard/profile.html.erb
<%= render 'shared/user_dash_nav' %>
<%= render 'devise/registrations/test' %>