config/routes.rb
Rails.application.routes.draw do
  resources :act_joins
  resources :user_logs
  resources :types, only: [:index, :show]

  resources :topics, only: [:index, :show]

  namespace :admin do
    resources :users
    resources :activities
    resources :blogs
    resources :topics
    resources :types

    root to: "users#index"
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :activities, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'draft-events', to: 'activities#draft'
  get 'activity/:id', to: 'activities#show', as: "activity_show"
  get 'user-dashboard', to: 'user_dashboard#index'
  post "user-dashboard"            => "user_dashboard#update"
  get 'user-profile', to: 'user_dashboard#profile'
  get 'user-activities', to: 'user_dashboard#active_activities'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'ranking', to: 'pages#ranking'
  get 'tweets', to: 'pages#tweets'

  resources :blogs, :activities do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/activity.rb
require 'date'

class Activity < ApplicationRecord
  belongs_to :type
  belongs_to :user
  has_many :act_joins, dependent: :destroy

  enum status: { draft: 0, live: 1, ended: 2 }

  validates_presence_of :title, :miles, :status, :description, :start_date, :end_date, :user_id, :type_id

  mount_uploader :image, ActivityUploader

  scope :activities_by, ->(user) { where(user_id: user.id) }

  scope :all_except, ->(activity) { where.not(status: 2) }

  def self.draft
    where(status: 'draft')
  end

  def self.live
    where(status: 'live')
  end

  def self.ended
    where(status: 'ended')
  end

  def self.by_position
    order("position ASC")
  end

  def self.recent
    order("created_at DESC")
  end

  after_create :toggle_status

  def toggle_status
    if self.end_date < Date.today
      self.update(status: 2)
    elsif self.start_date > Date.today
      self.update(status: 0)
    else self.start_date <= Date.today
      self.update(status: 1)
    end
  end

end

  

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity_item, only: [:edit, :update, :destroy, :show]
  before_action :set_sidebar_types, except: [:update, :create, :destroy]

  require 'date'
  layout "activity"
  # access all: [:show, :index], user: {except: [:destroy, :edit]}, site_admin: :all
  
  def index
    if logged_in?(:site_admin)
      @activity_events = Activity.recent.page(params[:page]).per(9).by_position
    else
      @activity_events = Activity.all_except(Activity.ended).recent.page(params[:page]).per(9).by_position
    end
  end

  def sort
    params[:order].each do |key, value|
      Activity.find(value[:id]).update(position: value[:position])
    end

    render nothing: :true
  end

  def draft
    @draft_events = Activity.draft
  end

  def new
    if logged_in?(:user) && current_user.try(:name) != "Guest User"
      @activity_events = current_user.activities.new
    else
      redirect_to root_path, notice: "You are not authorized to access this page"
    end
  end

  def create
    @activity_events = current_user.activities.new(activity_params)

    respond_to do |format|
      if @activity_events.save!
        format.html { redirect_to activities_path, notice: 'Your event was successfully created.' }
        format.json { render :show, status: :created, location: @activity_events }
      else
        format.html { render :new }
        format.json { render json: @activity_events.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @activity_events
  end

  def update
    authorize @activity_events

    respond_to do |format|
      if @activity_events.update(activity_params)
        format.html { redirect_to activities_path, notice: 'Your activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_events }
      else
        format.html { render :edit }
        format.json { render json: @activity_events.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @act_joins = ActJoin.new
    
    @page_title = @activity_events.title

    @user_activities = Activity.activities_by current_user
  end

  def destroy
    authorize @activity_events
    
    @activity_events.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully Deleted.' }
      format.json { head :no_content }
    end
  end 


  private

  def activity_params
    params.require(:activity).permit(:title, 
                                     :description, 
                                     :miles, 
                                     :image,
                                     :status,
                                     :end_date,
                                     :start_date,
                                     :user_id,
                                     :type_id
                                     )
  end

  def set_activity_item
    @activity_events = Activity.find(params[:id])
  end

  def set_sidebar_types
    @sidebar_types  = Type.with_activities
  end

end

app/controllers/admin/activities_controller.rb
module Admin
  class ActivitiesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    def display_resource(user)
      user.name
    end
    # def index
    #   super
    #   @resources = Activity.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Activity.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def image_generator
    "logo-rtd.png"
  end

  def act_img img, type
    if img.model.image?
      img
    else type == 'image'
      image_generator
    end 
  end
end

app/views/activities/_activity_event.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <%= image_tag act_img(activity_event.image, 'image'), height:'275px', width:'270px' %>
    <div class="card-body">
      <p class="card-text"><strong><%= link_to activity_event.title.truncate_words(6), activity_show_path(activity_event) %></strong></p>
      <div class="d-flex justify-content-between align-items-center">
        <ul class="list-unstyled mb-0">
          <li><small class="text-muted"><strong>Start Date: </strong><%= activity_event.start_date %></small></li>
          <li><small class="text-muted"><strong>Miles: </strong><%= activity_event.miles %></small></li>    
          <li><small class="text-muted"><strong>Status: </strong><%= activity_event.status %></small></li> 

        </ul>   
      </div>
    </div>
  </div>
</div>

app/views/activities/_countdown.html.erb
<div id="dueDate-counter">
  <% if @activity_events.end_date < Date.today %>
    <% @activity_events.update(status: 2) %>
      <table>
        <tr>
          <td><strong>Ended</strong></td><td></td>
        </tr>            
      </table>


  <% elsif @activity_events.start_date > Date.today %>
    <% @activity_events.update(status: 0) %>
      <table>
        <tr>
          <td><strong>Until</strong></td><td><strong>Start:</strong></td>
          <td><i>Days:</i></td><td id="days"></td><td>|</td>
          <td><i>Hrs:</i></td><td id="hours"></td><td>|</td>
          <td><i>Mins:</i></td><td id="minutes"></td><td>|</td>
          <td><i>Secs:</i></td><td id="seconds"></td>
        </tr>            
      </table> 
      <script type="text/javascript">
        function countdown() {
          var now = new Date();
          var eventDate = new Date("<%= @activity_events.start_date %>");
          var currentTime = now.getTime();
          var eventTime = eventDate.getTime();

          var remTime = eventTime - currentTime;

          var s = Math.floor(remTime / 1000);
          var m = Math.floor(s / 60);
          var h = Math.floor(m / 60);
          var d = Math.floor(h / 24);

          h %= 24;
          m %= 60;
          s %= 60;

          h = (h < 10) ? "0" + h : h;
          m = (m < 10) ? "0" + m : m;
          s = (s < 10) ? "0" + s : s;

          document.getElementById("days").textContent = d;
          document.getElementById("days").innerText = d;

          document.getElementById("hours").textContent = h;
          document.getElementById("minutes").textContent = m;
          document.getElementById("seconds").textContent = s;

          setTimeout(countdown, 1000);
        }

        countdown();
      </script>
    

    <% else @activity_events.start_date <= Date.today %>
      <% @activity_events.update(status: 1) %>

      <table>
        <tr>
          <td><strong>Time</strong></td><td><strong>Remaining:</strong></td>
          <td><i>Days:</i></td><td id="days"></td><td>|</td>
          <td><i>Hrs:</i></td><td id="hours"></td><td>|</td>
          <td><i>Mins:</i></td><td id="minutes"></td><td>|</td>
          <td><i>Secs:</i></td><td id="seconds"></td>
        </tr>            
      </table> 
      <script type="text/javascript">
        function countdown() {
          var now = new Date();
          var eventDate = new Date("<%= @activity_events.end_date %>");
          var currentTime = now.getTime();
          var eventTime = eventDate.getTime();

          var remTime = eventTime - currentTime;

          var s = Math.floor(remTime / 1000);
          var m = Math.floor(s / 60);
          var h = Math.floor(m / 60);
          var d = Math.floor(h / 24);

          h %= 24;
          m %= 60;
          s %= 60;

          h = (h < 10) ? "0" + h : h;
          m = (m < 10) ? "0" + m : m;
          s = (s < 10) ? "0" + s : s;

          document.getElementById("days").textContent = d;
          document.getElementById("days").innerText = d;

          document.getElementById("hours").textContent = h;
          document.getElementById("minutes").textContent = m;
          document.getElementById("seconds").textContent = s;

          setTimeout(countdown, 1000);
        }

        countdown();
      </script>
  <% end %>
              
</div>

app/views/activities/_form.html.erb
<%= form_with(model: @activity_events, local: true) do |form| %>
  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", rows: 10 %>
      </div>

      <div class="actions">
        <%= form.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :miles %>
        <%= form.number_field :miles, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :start_date %>
        <%= form.datetime_field :start_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :end_date %>
        <%= form.datetime_field :end_date, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload An Image <%= form.file_field :image, style: 'display:none;' %>
        </label>
        <small><em>Image Optional</em></small>
      </div>

      <h3>Activity Type</h3>
      <div>
        <%= form.label :type_id %>
        <%= form.collection_select(:type_id, Type.all, :id, :title, 
                                    {
                                      selected: @activity_events.type_id,
                                      include_blank: true
                                    },
                                     class: 'form-control'
                                  )
        %>
      </div>

      
    </div>
  </div>
<% end %>

app/views/activities/_type_fields.html.erb
<div class="form-group nested-fields">

</div>

app/views/activities/draft.html.erb
<h1>Draft Events</h1>

<%= link_to "Create New Event", new_activity_url %>

<% @draft_events.each do |event| %>
  <p><strong><%= link_to event.title, activity_show_path(event) %></strong></p>
  <p>Miles for Event:<%= event.miles %></p>
  <p><%= link_to event.status, toggle_status_activity_path(event) %></p>
  <%= link_to "Edit", edit_activity_path(event) %>
  <%= link_to 'Delete', activity_path(event), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/activities/edit.html.erb
<header class="masthead">
  <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Edit Activity</h1>
            <span class="subheading"></span>
          </div>
        </div>
      </div>
    </div>
  </div>  
</header>


<div class="card" style="width: 65rem;">
  <div class="card-body">
    <%= render 'form', activity_events: @activity_events %>
    
    <div class="auth-link">
      <%= link_to 'Back', activities_path %>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<header class="masthead">
  <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Activity Page</h1>
            <span class="subheading">Where You Can Join or Create Events</span>
          </div>
        </div>
      </div>
    </div>
  </div>  
</header>



<div>
  <%= render 'shared/activity_search_bar' %>
</div>

<div class="album py-5">
  <div class="container">
    <div class="row">

      <%= render partial: 'activity_event', collection: @activity_events %>   
    </div>
    <%= paginate @activity_events %>
  </div>
</div>

app/views/activities/new.html.erb
<header class="masthead">
  <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Create a Activity</h1>
            <span class="subheading">Challenge yourself and others with these events</span>
          </div>
        </div>
      </div>
    </div>
  </div>  
</header>

<div class="card" style="width: 65rem;">
  <div class="card-body">
    <%= render 'form', activity_events: @activity_events %>
    
    <div class="auth-link">
      <%= link_to 'Back', activities_path %>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-heading">
          <h1><%= @activity_events.title %></h1>
          <span class="meta">Posted by
            <a href="#"><%= link_to @activity_events.user.name.upcase %></a></span>
        </div>
      </div>
    </div>
  </div>
</header>


<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <div class="left">
        Miles: <%= @activity_events.miles %>
      </div>
      <div class="right">
        Start Date: <%= @activity_events.start_date %>  
      </div>
      <div class="right">
        End Date: <%= @activity_events.end_date %>
       </div> 
    </div>
    <div class="card-body">
      <h5 class="card-title">Description:</h5>
      <p class="card-text"><%= @activity_events.description %></p>
      
      <% if current_user.try(:role) == :site_admin || current_user.try(:role) == :user && current_user.try(:name) != "Guest User" %>
        <div class="btn-group">
          <%= render 'act_joins/act_join_form' %>
        </div>
      <% end %>

    </div>
    <div class="card-footer text-muted">
      <div class="left">
        <%= render 'countdown' %>
      </div>
      <div class="right">
        Event Type: <%= @activity_events.type.title %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="card text-center">
    <div class="col-md-12">
      <h3 class="pb-3 mb-4 font-italic border-bottom">
        Joined Users:
      </h3>
      <%= render @activity_events.act_joins %>
    </div>   
  </div>
</div>